/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.truthencode.plugins.example

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.Task

/**
 * A simple 'hello world' plugin.
 */
class PocGradlePluginPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register("doSomething") {
            doLast {

            }
        }
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'io.truthencode.plugins.example.greeting'")
            }
        }
    }
}
