/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package io.truthencode.poc.kantlr.app

import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.CommonTokenStream
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class ParserTest {
    @Test
    fun testGetMessage() {
        val ar = "(init { (value 4) , (value 5) , (value 323) })"
        val input = CharStreams.fromString("{4,5,323}", "lary")
        val lexer = io.truthencode.poc.kantlr.app.ArrayInitLexer(input)
        val tokens = CommonTokenStream(lexer)
        val parser = io.truthencode.poc.kantlr.app.ArrayInitParser(tokens)

        val tree = parser.init()

        assertEquals(ar, tree.toStringTree(parser))
    }

    @Test
    fun testRefEnchantmentParser() {
        val p: io.truthencode.ddo.grammar.antlr.EnchantmentsParser
    }
}