version: '{build}'
os: Windows Server 2012
build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
- gradlew.bat check acceptanceTest --info --no-daemon

cache:
- C:\Users\appveyor\.gradle