#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2015-2021 Andre White.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Override via the command line to change the default Java toolchain version.
# Included build has a fallback constant if this is somehow missing
# TODO: add validation to ensure the version is valid
defaultJavaToolChainVersion=21

# Override via the command line to change the default Scala Library
# Included build has a fallback constant if this is somehow missing
builderScalaVersion=3

# JVM / System args / Gradle Properties
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m
org.gradle.workers.max=2
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

# Kotlin Specific
kotlin.daemon.jvm.options="-Xmx512m"
kotlin.code.style=official

# Quarkus Related
quarkusPluginId=io.quarkus
# TODO: merge Quarkus platform and plugin versions into single property and move to version catalog
quarkusPluginVersion=3.39.5
quarkusPlatformVersion=3.39.5
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom

# use catalog as source of truth for dependencies

# TODO: move koTestVerson to version catalog
koTestVersion=5.5.5
# Settings Plugins (can't use version catalogs)
# foojay
foojayResolverPluginVersionversion=0.4.0

# semver and deployment
mooltiverseNyxPluginVersion=3.1.7

# Build configuration @see settings.gradle.kts
projectFolderDelimiter=,
projectFolders=generated,profiles,docs,subprojects

# Catalog Version Updater properties
nl.littlerobots.vcu.resolver=true

# Dependency Version
#refreshVersionsPluginVersion=0.60.5 # Phasing out in favor of catalog updater

# Version alias for mkdocs, overrides default 'Latest' when specified.
mkDocsLatestAlias=Current

##Avro / OpenAPI
##Avro related
# TODO: move avroHuggerPluginVersion to version catalog
avroHuggerPluginVersion = 0.8.1


