/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.7.0/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
import java.nio.file.Files
import java.nio.file.Paths

rootProject.name = "ddo-calc-parent"
pluginManagement {
    val mooltiverseNyxPluginVersion = providers.gradleProperty("mooltiverseNyxPluginVersion")
    val foojayResolverPluginVersionversion = providers.gradleProperty("foojayResolverPluginVersionversion")

    plugins {
//        id("com.mooltiverse.oss.nyx") version mooltiverseNyxPluginVersion
        id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
        id("com.gradle.develocity") version ("4.5.0") // Gradle 6.x + older versions must apply at root project
    }

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {

//    id("com.mooltiverse.oss.nyx")
    id("org.gradle.toolchains.foojay-resolver-convention")
//    id("com.gradle.develocity")
}

// need a property toggle so we don't double scan inside IDEA
// develocity {
//    buildScan {
//          tag(if (System.getenv("CI").isNullOrEmpty()) "Local" else "CI")
//        tag(System.getProperty("os.name"))
//        termsOfUseAgree = "yes"
//        // termsOfServiceUrl = "https://gradle.com/terms-of-service"
//        // termsOfServiceAgree = "yes"
//    }
// }
// at some point in the future, see if we can safely make this property optional so there is no build warning if it is
// not specified or create a sensible default
val defaultDelimiter = " "
val projectFolderDelimiter = providers.gradleProperty("projectFolderDelimiter").getOrElse(defaultDelimiter)

@Suppress("CUSTOM_GETTERS_SETTERS")
val projectFolders: List<String>
    get() =
        providers.gradleProperty("projectFolders").getOrElse("").split(projectFolderDelimiter)

logger.info("checking $projectFolders for sub-projects")

/**
 *  reads the first part of a string up to the "."
 *  should be an Extension, but cannot inline compile as one in settings.gradle.kts
 *
 *  so we're doing a quick one-off verses polluting a buildSrc, um... further
 *
 *  @param str the string to parse
 *  @return the first part of the string
 */
fun readFirstPart(str: String): String = str.split(".").first()

logger.debug("checking ${projectFolders.size} project folders")
projectFolders.forEach { dirName ->
    val directory = Paths.get("$rootDir/$dirName")
    if (Files.notExists(directory)) {
        logger.warn("$directory does not exist,  creating")
        Files.createDirectory(directory)
    }

    Files
        .find(
            directory,
            Integer.MAX_VALUE,
            { _: java.nio.file.Path, attributes: java.nio.file.attribute.BasicFileAttributes ->
                attributes.isDirectory
            },
        ).use { dir ->
            dir.forEach { dr ->
                val customName = dr.toFile().name
                // ({{f,s -> true}})
                val files =
                    dr
                        .toFile()
                        .listFiles { _, str -> str.matches(Regex("($customName|build)\\.gradle(\\.kts)?")) }

                if (files?.isEmpty() != true) {
                    if (files!!.size != 1) {
                        logger.warn("Multiple build files located in project directory $dr")
                    }
                    val projectDir = rootDir.toPath().relativize(dr)
                    val first = files.first()
                    val buildFileName = first.name
                    // build file name may be arbitrary but usually follows either build or the directory name.
                    // since we're mostly controlling the build we'll assume the containing folders' name.
                    val projectName = first.parentFile.name
                    logger.debug("Including Project:$projectName \tprojectDir: $projectDir \tBuildFile: $buildFileName")
                    include(projectName)
                    project(":$projectName").projectDir = projectDir.toFile()
                    project(":$projectName").buildFileName = buildFileName
                }
            }
        }
}

if (System.getenv("enableCompositeBuild") == "true") {
    logger.debug("Adding included builds")
    file("examples").listFiles()?.filter { ft -> ft.isDirectory }?.forEach { moduleBuild: File ->
        includeBuild(moduleBuild)
    }
}
//
// @Suppress("UnstableApiUsage")
// refreshVersions {
//    // https://github.com/jmfayard/refreshVersions
//    rejectVersionIf {
//        candidate.stabilityLevel.isLessStableThan(StabilityLevel.Stable)
//    }
//    featureFlags {
//        this.enable(FeatureFlag.VERSIONS_CATALOG)
//    }
// }
includeBuild("build-logic")
