/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2015-2021 Andre White.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package io.truthencode.ddo.modeling

import org.scalatest.funspec.AnyFunSpec

class LibrarySuite extends AnyFunSpec {
  describe("someLibraryMethod is always true") {
    def library: Library = new Library()
    assert(library.someLibraryMethod())
  }

  describe("Something magical") {
    it("can fluctuate") {
      val vc = io.truthencode.ddo.model.protocol.ChangeType
    }
  }
}
