[versions]
ch-qos-logback = "1.4.11"
com-wix = "0.7.6"
io-getquill = "4.6.1"
io-monix = "3.4.1"
org-jetbrains-kotlin = "1.9.0"
org-junit-jupiter = "5.10.0"
org-scoverage = "2.0.10"

[libraries]
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback" }
co-helmethair-scalatest-junit-runner = "co.helmethair:scalatest-junit-runner:0.2.0"
com-beachape-enumeratum_2-13 = "com.beachape:enumeratum_2.13:1.7.3"
com-geirsson-scalafmt-core_2-13 = "com.geirsson:scalafmt-core_2.13:3.1.1"
com-github-kxbmap-configs_2-13 = "com.github.kxbmap:configs_2.13:0.6.1"
com-typesafe-config = "com.typesafe:config:1.4.2"
com-typesafe-scala-logging-scala-logging_2-13 = "com.typesafe.scala-logging:scala-logging_2.13:3.9.5"
com-wix-accord-core_2-13 = { module = "com.wix:accord-core_2.13", version.ref = "com-wix" }
com-wix-accord-scalatest_2-13 = { module = "com.wix:accord-scalatest_2.13", version.ref = "com-wix" }
de-neuland-bfi-jade4j = "de.neuland-bfi:jade4j:1.3.2"
io-getquill-quill-core_2-13 = { module = "io.getquill:quill-core_2.13", version.ref = "io-getquill" }
io-getquill-quill-monix_2-13 = { module = "io.getquill:quill-monix_2.13", version.ref = "io-getquill" }
io-getquill-quill-sql_2-13 = { module = "io.getquill:quill-sql_2.13", version.ref = "io-getquill" }
io-monix-monix-eval_2-13 = { module = "io.monix:monix-eval_2.13", version.ref = "io-monix" }
io-monix-monix-reactive_2-13 = { module = "io.monix:monix-reactive_2.13", version.ref = "io-monix" }
net-ruippeixotog-scala-scraper_2-13 = "net.ruippeixotog:scala-scraper_2.13:3.1.0"
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:3.0.0-alpha1"
org-concordion = "org.concordion:concordion:4.0.1"
org-concordion-concordion-collapse-output-extension = "org.concordion:concordion-collapse-output-extension:1.0.0"
org-concordion-concordion-embed-extension = "org.concordion:concordion-embed-extension:1.2.0"
org-jetbrains-annotations = "org.jetbrains:annotations:24.0.1"
org-jetbrains-kotlin-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "org-jetbrains-kotlin" }
org-json4s-json4s-native_2-13 = "org.json4s:json4s-native_2.13:4.1.0-M3"
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "org-junit-jupiter" }
org-junit-platform-junit-platform-engine = "org.junit.platform:junit-platform-engine:1.10.0"
org-junit-platform-junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.10.0"
org-junit-platform-junit-platform-runner = "org.junit.platform:junit-platform-runner:5.8.2"
org-junit-vintage-junit-vintage-engine = "org.junit.vintage:junit-vintage-engine:5.10.0"
org-mockito-mockito-core = "org.mockito:mockito-core:5.5.0"
org-scalacheck-scalacheck_2-13 = "org.scalacheck:scalacheck_2.13:1.17.0"
org-scalatest-scalatest_2-13 = "org.scalatest:scalatest_2.13:3.3.0-SNAP4"
org-scalatestplus-mockito-3-4_2-13 = "org.scalatestplus:mockito-3-4_2.13:3.3.0.0-SNAP3"
org-scoverage-scalac-scoverage-runtime_2-13 = { module = "org.scoverage:scalac-scoverage-runtime_2.13", version.ref = "org-scoverage" }

[plugins]
com-dorongold-task-tree = "com.dorongold.task-tree:2.1.1"
com-github-ManifestClasspath = "com.github.ManifestClasspath:0.1.0-RELEASE"
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.48.0"
com-zlad-gradle-avrohugger = "com.zlad.gradle.avrohugger:0.7.0"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.1"
org-openapi-generator = "org.openapi.generator:7.0.0"
