-- Automatically generated by ddo-etl
create or replace
function fn_feat_activity(feat_name character varying, feat_description character varying)
	returns integer as
'
declare v_id integer;

begin
insert
	into
	${table} (name,
	description)
values (feat_name,
feat_description)
ON CONFLICT (NAME) DO NOTHING
returning id
into
	v_id;



if v_id is null then
select f.id into v_id
from ${table} f
where f.name = name;
end if;

return v_id;

end
'
language plpgsql volatile;

<#list feats>
<#items as feat>
<#assign seq = feat.usages()>
<#list seq>
<#items as usage>
INSERT INTO ${table}_usages (feat_id, usages)
SELECT  fn_feat_activity('${feat.name()}', '${feat.safeDesc()}'),'${usage}';
</#items>
</#list>
</#items>
</#list>
