-- Automatically generated by ddo-etl
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'Passive', false, true);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'Never', false, true);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnAttack', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnAttackRoll', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnDamage', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnSpellHit', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnSpellCast', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnSpellLikeAbility', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnSong', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnDeath', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnIncapacitated', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnRest', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnHealthy', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnHealthLevelBelow', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnHealthLevelAbove', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnToggle', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'AtWill', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnCoolDown', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'InTavern', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'SpecialAttack', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'Summon', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'ShapeChange', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnEquip', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnUnEquip', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnCentered', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnOffCentered', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnStance', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnUnconscious', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnTimer', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnTumble', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'WhileOn', true, false);
    INSERT INTO trigger_table (name, active, passive )
    VALUES( 'OnLevelUp', false, false);
